# Generated by Django 5.2.15 on 2026-06-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
    ]
