# Generated by Django 5.2.15 on 2026-06-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='paragraph1',
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
    ]
